### PR TITLE
Support laravel 6.x

### PR DESCRIPTION
**Pull request by fernandocoronatomf**
Support for laravel 6

### CODE REVIEW

**Comment by benrowe** [comment]
Awesome. Just what im looking for.

**Comment by whispli** [comment]
It would be great if this could be merged so we don't have to maintain a fork.

**Comment by rubenfunai-whispli** [comment]
It would be great if we could merge this so we don't have to maintain our own fork. :+1:

**Comment by ph4r05** [comment]
@rubenfunai-whispli thanks for the reminder. Merged.

**Comment by rubenfunai-whispli** [comment]
No worries! Thanks for merging it! :smiley:

**Pull request merged**
