### PR TITLE
Bump version to laravel 5.7

### PR DESCRIPTION
**Pull request by lazychaser**

### CODE REVIEW

**Comment by ph4r05** [comment]
Thanks for the PR, but there is something that needs to be solved w.r.t. queues

https://travis-ci.org/ph4r05/laravel-queue-database-ph4/jobs/443161933

**Comment by lazychaser** [comment]
What `testFailureToCreatePayloadFromObject` is for? This is where it fails because queue method signature changed.

**Comment by zilveer** [comment]
any update there?

**Comment by ghost** [comment]
@ph4r05 @lazychaser 

Tests failed because Laravel 5.7 requires extra param `$queue`. Please see below laravel 5.6 and 5.7
https://laravel.com/api/5.6/Illuminate/Queue/Queue.html#method_createPayload
https://laravel.com/api/5.7/Illuminate/Queue/Queue.html#method_createPayload

**Comment by ph4r05** [comment]
Fixed by #7. Anyway, many thanks for your contribution!

**Pull request closed without merging**
